<a href="https://colab.research.google.com/github/pupidly/INGENIA24/blob/main/IngeniasNotebook_5_DY.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Programa Ingenias+ Data Science

Como dijimos en clases anteriores, Python tiene implementadas muchas librerias para poder trabajar con datos. En la clase de hoy trabajaremos con una de ellas: `Numpy`.

Antes de comenzar, vamos a hablar un poco de esta libreria o modulo.

**Numpy** es una librería optimizada para realizar cálculos numéricos con vectores y matrices. A diferencia de otros lenguajes de programación, Python no posee en su estructura central la figura de matrices. Eso quiere decir que para poder trabajar con esta estructura de datos deberiamos trabajar con listas de listas. NumPy introduce el concepto de arrays o matrices.

Al ser de código abierto, `numpy` posee una documentación muy amplia que es **SIEMPRE RECOMENDABLE** consultar.

- [Documentacion NumPy](https://devdocs.io/numpy/)

## Clase 4: Introduccion a NumPy

# Ejercicios

1. Crear un arreglo de ceros de longitud 12
2. Crear un arreglo de longitud 10 con ceros en todas sus posiciones y un 10 en la posición número 5
3. Crear un arreglo que tenga los números del 10 al 49
4. Crear una arreglo 2d de shape (3, 3) que tenga los números del 0 al 8
5. Crear un arreglo de números aleatorios de longitud 100 y obtener su media y varianza
6. Calcular la media de un arreglo usando np.sum
7. Calcular la varianza de un arreglo usando np.sum y np.mean
8. Crear un array de números aleatorios usando np.random.randn.


In [8]:
import numpy as np
import pandas as pd

In [22]:
#Ejercicio 1: Crear un arreglo de ceros de longitud 12

arreglo1 = np.zeros(12)
arreglo1

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [23]:
#Ejercicio 2: Crear un arreglo de longitud 10 con ceros en todas sus posiciones y un 10 en la posición número 5

arreglo2 = np.zeros(10)
arreglo2[4]= 10            #entiendo la 5ta posicion contando desde el 0
arreglo2

array([ 0.,  0.,  0.,  0., 10.,  0.,  0.,  0.,  0.,  0.])

In [24]:
#Ejercicio 3: Crear un arreglo que tenga los números del 10 al 49

arreglo3 = np.arange(10, 50, 1)
arreglo3


array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

In [37]:
#Ejercicio 4: Crear una arreglo 2d de shape (3, 3) que tenga los números del 0 al 8

arreglo4 = np.arange(0, 9, 1)
arreglo4.shape = (3, 3)
arreglo4


array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [31]:
#Ejercicio 5: Crear un arreglo de números aleatorios de longitud 100 y obtener su media y varianza

arreglo5 = np.random.randint(1, 100, 100)
print(arreglo5)
print(f'El valor medio es:{np.mean(arreglo5)}')
print(f'El valor de la varianza es:{np.var(arreglo5)}')

[10 77 16 90 65 65  5 89 15 68  7 28 16 10 62 66 78 48 56 74 78 37 83 30
 76 14 29 17 65 46 31 73 67 94 29 49  4 14 20 13 72 77 43 46  8 49 34 40
 29  1 43 69 65 82 83 43 22 81 44  3 41 18 27 10 21  4 68  9 62 55 13 83
 25 63 24 32 32 74 84 90 21 22 82 37 96 65 55 65  4 18 98 83 28  1 16 63
 78 88 37 19]
El valor medio es:45.59
El valor de la varianza es:798.0819


In [32]:
#Ejercicio 6: Calcular la media de un arreglo usando np.sum

media_arr5 = np.sum(arreglo5)/len(arreglo5)
print(f'la media del arreglo del ejercio anterior calculada con sum da: {media_arr5}')

la media del arreglo del ejercio anterior calculada con sum da: 45.59


In [33]:
#Ejercicio 7: Calcular la varianza de un arreglo usando np.sum y np.mean

media = np.mean(arreglo5)
desvCuad = (arreglo5 - media)**2
var_arr5 = np.sum(desvCuad)/len(arreglo5)
print(f'la varianza del arreglo calculada da: {var_arr5}')

la varianza del arreglo calculada da: 798.0819


In [39]:
#Ejercicio 8: Crear un array de números aleatorios usando np.random.randn.

array6 = np.random.randn(10)
array6

array([-0.49052716, -0.14955447,  1.61350225, -0.81950666, -0.2103647 ,
        0.98918573, -1.08199832,  0.53223469,  1.40678442,  0.35799492])